### PR TITLE
Lots of minor code and formatting improvements

### PR DESCRIPTION
**Pull request by UncleThaodan**
I highly, highly recommend using Autopep8 (ignoring rule E501). It keeps your formatting consistent and helps prevent certain bugs.

I fixed a whole bunch of formatting issues and made some minor improvements to the code.
I also noticed a potential issue in AMP_cog.py at line 280 and marked it with a TODO.

The changes are all in individual commits to help with cherry-picking/noise.

### CODE REVIEW

**Review by k8thekat — DISMISSED** [review]
No issue with these changes as they are purely formatting changes.

**Comment by k8thekat** [comment]
Going to PR to a new branch for testing purpose. I want to look through the changes further and do testing as to not conflict with my "devtesting" branch.

Thank you for your PR

**Review by k8thekat — CHANGES_REQUESTED** [review]
Could you please revert any f-string changes.
Thank you.

**Comment by UncleThaodan** [comment]
Do you mean the ones in [a610030](https://github.com/k8thekat/GatekeeperV2/pull/26/commits/a610030850725852ec67e6695ef45ee2208f8fb2), [9457580](https://github.com/k8thekat/GatekeeperV2/pull/26/commits/94575809b7881e0f8b9c637dc39425b89ab07cd4) or both?

**Comment by k8thekat** [comment]
Any of the unused f-strings are fine in [94575](https://github.com/k8thekat/GatekeeperV2/pull/26/commits/94575809b7881e0f8b9c637dc39425b89ab07cd4), but remove the others please. Same goes for [a610030](https://github.com/k8thekat/GatekeeperV2/pull/26/commits/a610030850725852ec67e6695ef45ee2208f8fb2)
 
 Thanks.

**Review by k8thekat — APPROVED** [review]

**Comment by k8thekat** [comment]
Thank you. Approving the PR.

**Pull request merged**
